version: '3.8'

services:

  postgres:
    container_name: postgres-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Antivirus9936
      - POSTGRES_DB=onlineshopping
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: online-shopping-app
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4444:4444"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=Antivirus9936
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=onlineshopping
      - JWT_SECRET_KEY=secret
      - SMPT_HOST=smtp.gmail.com
      - SMPT_PORT=465
      - SMPT_SERVICE=gmail
      - SMPT_USER=doniyorqalandarov853@gmail.com
      - SMPT_PASSWORD="eety weff ncot fsez"
    depends_on:
      - postgres
    command: [ "npm", "start:prod" ]

volumes:
  postgres-data:
